name: Deploy da Calculadora
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  contents: read 
  
concurrency:
  group: "grupo-unico"
  cancel-in-progress: false
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extrair do GitHub
        uses: actions/checkout@v4
      - name: Configurar o GitPages
        uses: actions/configure-pages@v5
      - name: Fazer upload dos arquivos no GitPages
        uses: actions/upload-pages-artifact@v3
      - name: Implantar
        uses: actions/deploy-pages@v4
        
